python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_allegro5 TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_allegro5.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_android TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_android.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_dx9 TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_dx9.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_dx10 TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_dx10.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_dx11 TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_dx11.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_dx12 TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_dx12.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_glfw TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_glfw.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_glut TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_glut.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_opengl2 TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_opengl2.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_opengl3 TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_opengl3.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_sdl2 TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_sdl2.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_sdlrenderer2 TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_sdlrenderer2.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_sdl3 TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_sdl3.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_sdlrenderer3 TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_sdlrenderer3.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_vulkan TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_vulkan.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_wgpu TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_wgpu.h
python dear_bindings.py --backend -o TestCode\sdl2-cimgui-demo\generated\cimgui_impl_win32 TestCode\sdl2-cimgui-demo\externals\cimgui\imgui\backends\imgui_impl_win32.h
