from . import mod_remove_pragma_once
from . import mod_flatten_namespaces
from . import mod_attach_preceding_comments
from . import mod_remove_function_bodies
from . import mod_remove_operators
from . import mod_remove_structs
from . import mod_remove_functions
from . import mod_remove_all_fields_from_classes
from . import mod_add_prefix_to_loose_functions
from . import mod_flatten_class_functions
from . import mod_flatten_nested_classes
from . import mod_flatten_inheritance
from . import mod_flatten_templates
from . import mod_flatten_conditionals
from . import mod_disambiguate_functions
from . import mod_convert_by_value_struct_args_to_pointers
from . import mod_convert_references_to_pointers
from . import mod_remove_static_fields
from . import mod_remove_extern_fields
from . import mod_remove_nested_typedefs
from . import mod_remove_all_functions_from_classes
from . import mod_merge_blank_lines
from . import mod_remove_blank_lines
from . import mod_remove_enum_forward_declarations
from . import mod_remove_empty_conditionals
from . import mod_make_all_functions_use_imgui_api
from . import mod_rename_defines
from . import mod_rename_functions
from . import mod_rename_function_by_signature
from . import mod_forward_declare_structs
from . import mod_mark_by_value_structs
from . import mod_add_includes
from . import mod_change_includes
from . import mod_remove_includes
from . import mod_remove_heap_constructors_and_destructors
from . import mod_generate_default_argument_functions
from . import mod_generate_imstr_helpers
from . import mod_align_comments
from . import mod_align_enum_values
from . import mod_align_function_names
from . import mod_align_structure_field_names
from . import mod_add_manual_helper_functions
from . import mod_add_function_comment
from . import mod_mark_internal_members
from . import mod_exclude_defines_from_metadata
from . import mod_wrap_with_extern_c
from . import mod_remove_constexpr
from . import mod_assign_anonymous_type_names
from . import mod_add_forward_declarations
from . import mod_calculate_enum_values
from . import mod_mark_special_enum_values
from . import mod_mark_flags_enums
from . import mod_add_unformatted_functions
from . import mod_rewrite_containing_preprocessor_conditional
from . import mod_mark_structs_as_using_unmodified_name_for_typedef
from . import mod_mark_types_for_pointer_cast
from . import mod_set_arguments_as_nullable
from . import mod_remove_defines
from . import mod_rewrite_defines
from . import mod_move_elements
from . import mod_remove_typedefs
from . import mod_replace_typedef_with_opaque_buffer
from . import mod_change_class_field_type
from . import mod_rename_prefix
from . import mod_mark_structs_as_single_line_definition