// Autogenerated code

#include "imgui.h"
#include "imgui_internal.h"
#include <stdio.h>

// API for exported functions
#define IMGUI_CAPI extern "C"

// Helper functions
namespace ImGui
{
    void LogTextV(const char* fmt, va_list args)
    {
        // Fixme: Add this to the main library rather than using this hack
        ImGuiContext& g = *GImGui;
        if (!g.LogEnabled)
            return;

        if (g.LogFile)
            vfprintf(g.LogFile, fmt, args);
        else
            g.LogBuffer.appendfv(fmt, args);
    }
}
